version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./pfm_pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=pfm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
